CREATE TABLE IF NOT EXISTS person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName varchar(20) NOT NULL,
    lastName varchar(20) NOT NULL,
    username varchar(20) NOT NULL,
    email varchar(100) UNIQUE,
    numberPhone varchar(11) UNIQUE,
    age INT CHECK(age>10),
    role varchar(100) not null
    password varchar
);

CREATE TABLE  IF NOT EXISTS craftsmen (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    specialization varchar NULL,
    info_about_master varchar NULL,
    person_id int UNIQUE REFERENCES person(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT exists days_of_the_craftsmen(
    id int primary key GENERATED BY DEFAULT AS IDENTITY,
    days_work Date
);

CREATE TABLE IF NOT exists days_work (
    craftsmen_id INTEGER not null references craftsmen,
    days_of_the_craftsmen_id INTEGER not null references days_of_the_craftsmen,
    FOREIGN KEY (craftsmen_id) REFERENCES craftsmen(id),
    FOREIGN KEY (days_of_the_craftsmen_id)REFERENCES days_of_the_craftsmen(id),
    UNIQUE (days_of_the_craftsmen_id, craftsmen_id)
);

CREATE TABLE IF NOT exists make_an_appointment (
    id int primary key GENERATED BY DEFAULT AS IDENTITY,
    data_record Date,
    time_record Date,
    beauty_sercice varchar not null,
    person_id integer not null references person,
    craftsmen_id integer not null references craftsmen,
    UNIQUE (person_id, craftsmen_id) // в бд без этой строки для отладки
);